### ISSUE TITLE
RangeError: toFixed() digits argument must be between 0 and 20 at variety.js:304

### ISSUE THREAD

**Issue by joergrech** [variety/variety#100]
When I run variety.js on MongoDB 3.0.4 and TokuMX 2.0.1 using the following line
`mongo localhost:27017/database --eval "var collection = 'profile'" variety.js > out.json`
I get the following error after some time (roughly 4 hours):
```
Using collection of "profile"
Using query of { }
Using limit of 32030435
Using maxDepth of 99
Using sort of { "_id" : -1 }
Using outputFormat of "ascii"
Using persistResults of false
Using plugins of [ ]
Sun Jul 26 13:17:16.060 RangeError: toFixed() digits argument must be between 0 and 20 at variety.js:304
failed to load: variety.js
```
My collection has 32 Million documents. Any hint what could be wrong?

**Comment by JamesCropcho** [comment]
Hello Jörg,

I wish I could help. I actually have no idea. Anybody else?

I managed to find a handful of results by Googling (with quotation marks) `"RangeError: toFixed() digits argument must be between 0 and 20"`.

Based on the large size of the dataset, it may be something about JavaScript reaching floats/integers which are too large to hold in memory maybe?

Perhaps you could try to supply a `limit` parameter, and effectively take a (hopefully) representative sample.

**Comment by joergrech** [comment]
You are right that it works with limit. I could run it using 1 Millionen and 10 Millionen and used sort to identify some of my more interesting documents. 

Whatever the cause maybe it would be great for future users to get more explanations. Could you catch the Exception and return a hint towards the limit? Just a thought.

Nevertheless - Thanks,
Joerg
