### ISSUE TITLE
simplest way to install and use as standard lib?

### ISSUE THREAD

**Issue by ppKrauss** [variety/variety#102]
What the simplest way to "plug and play" at terminal?
There are something like `mongo mydb < variety.js `  terminal command to store a a lib?

**Comment by JamesCropcho** [comment]
Hello Peter,

Thanks for trying out Variety. The answer to your question should be available at https://github.com/variety/variety#an-easy-example.


James

**Comment by todvora** [comment]
Hi @ppKrauss, 
from your question is not clear if you want to store variety inside mongo shell and reuse later (see #21) or you simply want to run variety from terminal. 

The first option is currently not possible. From the terminal you can follow example mentioned by James. In case you are familiar with node.js check also https://github.com/variety/variety-cli.

Regards,
Tomas

**Comment by ppKrauss** [comment]
Hi @todvora , thanks, yes, I am not a mongodb expert, but it is #21... The ideia is like to plug a library into (persisting it ex. in the *public schema*)  of  PostgreSQL, `psql < lib.sql`, is very usefull.
