### ISSUE TITLE
Cannot use 'commands' readMode, degrading to 'legacy' mode

### ISSUE THREAD

**Issue by todvora** [variety/variety#113]
Hi everyone,
During testing of Variety, I hit following warning:

```
Cannot use 'commands' readMode, degrading to 'legacy' mode
```

It appears only when newer shell (3.2) is used for analysis against older database (lower than 3.0). There have been some changes in communication protocol introduced and this warning is produced only when fallback method used. 

The real problem for us is - **this warning cannot be muted** by `--quiet` option of mongo shell and thus **breaks JSON output**.  

To address this issue, I've created following pull request: https://github.com/mongodb/mongo/pull/1073. It has also its own Jira Issue: https://jira.mongodb.org/browse/SERVER-21745

Could you please upvote the issue or write a comment, to get things in motion? 

Thank you!
Tomas

**Comment by JamesCropcho** [comment]
Good find, Tomáš. I have upvoted the bug on Jira, and the related bug. Let me know what else I can do.


—James

**Comment by arthur-c** [comment]
Hi,
Same problem with shell 3.2.4, it breaks the output even with --quiet.

**Comment by todvora** [comment]
Hi Arthur, exactly - even with ```--quiet```. Could you please [upvote the jira issue](https://jira.mongodb.org/browse/SERVER-21745) too?

**Comment by arthur-c** [comment]
@todvora done

**Comment by JamesCropcho** [comment]
Huh. Well I guess we will leave this open for now. I don't know how long it'll take for Mongo to merge the PR.

**Comment by JamesCropcho** [comment]
Hello all, I wanted to mention that as of 17 minutes ago, the Jira issue for this is marked "Fixed": https://jira.mongodb.org/browse/SERVER-21745. Hopefully a happy step forward.

**Comment by sulthanallaudeen** [comment]
but the data was lost
