### ISSUE TITLE
can't not use authenticationDatabase in --eval ""

### ISSUE THREAD

**Issue by kimmy-github** [variety/variety#117]
hi, 
   I found a question about authenticationDatabase;There is my application sence,I want analyze DB1:tab1 ,and store the results into another DB2:tab2 ,and DB2:tab2 in different host:port using different user and pass; and user always create in admin database;Here is my command:
mongo ip1:1111/db1  -uuser1 -p*******  --authenticationDatabase=admin --quiet  --eval "var collection = 'users', persistResults=true,resultsDatabase='ip2:1112/results',resultsCollection='test',resultsUser='user2',resultsPass='*******'" variety.js

when I execute above command,I got a error:
connecting to: *****:1112/results
Fri May  6 14:45:40.335 Error: 18 { code: 18, ok: 0.0, errmsg: "auth fails" } at src/mongo/shell/db.js:228
exception: login failed

I foun the way to solve this error: create the user2 in results database;
I wonder if add the authenticationDatabase in variety scripts ?

**Comment by todvora** [comment]
Hi,
Thank you for bringing attention to this issue.

You are right, there is currently no support for ```authenticationDatabase``` used to authenticate user to results-persisting database. 

As you already found out, one of the solutions is to create a user in the ```resultsDatabase```. In such a complicated case I would probably prefer to perform the analysis locally, [output data into JSON](https://github.com/variety/variety#render-output-as-json-for-easy-ingestion-and-parsing) and transfer them into desired DB somehow on my own, without Variety. 

If this proves to be a common requirement, it may be implemented in the future (as we already support username/password anyway). Or you can go ahead and implement it. I'll gladly review, test and merge any pull request related to this issue.

Best regards,
Tomas

**Comment by JamesCropcho** [comment]
Hello you two, and happy Monday.

I am going to close this issue ticket since Kimmy's question may be resolved. But sincerely, if any party wants to pursue further, do re-open!


—James

**Comment by kimmy-github** [comment]
hi,todvora:
    thank you for replying .
