### ISSUE TITLE
Getting typeof data contained in an Array

### ISSUE THREAD

**Issue by damiannorman0** [variety/variety#120]
Just wondering if there is a way to get insight into the contents of the data when it is contained in an Array? I know when Variety finds an Object we can get each key and the typeof for each value, but I can't see a way to do this with content in Arrays.

**Comment by todvora** [comment]
Hi Damian,
Variety parses the content of arrays too. Take for example a collection (from [this test case](https://github.com/variety/variety/blob/master/spec/UnnamedObjectsAnalysisTest.js)):
```js
[
  {title:'Article 1', comments:[{author:'John', body:'it works', visible:true }]},
  {title:'Article 2', comments:[{author:'Tom', body:'thanks'}, {author:'Mark', body:1}]}
]
```
The  ```comments``` field is in both cases an array and contains nested objects. The result of analysis is then:

```
+----------------------------------------------------------------------+
| key                 | types                 | occurrences | percents |
| ------------------- | --------------------- | ----------- | -------- |
| _id                 | ObjectId              |           2 |    100.0 |
| comments            | Array                 |           2 |    100.0 |
| comments.XX.author  | String                |           2 |    100.0 |
| comments.XX.body    | String (2),Number (1) |           2 |    100.0 |
| title               | String                |           2 |    100.0 |
| comments.XX.visible | Boolean               |           1 |     50.0 |
+----------------------------------------------------------------------+
```
As you can see, those nested objects are analysed as ```XX.author```, ```XX.body``` and ```XX.visible``` keys. ```XX.``` is a prefix for objects inside an unnamed array.

Is it answer to your question?

Best regards,
Tomas

**Comment by damiannorman0** [comment]
Thanks for your help - I thought it must be possible. Presumably this output is fully available in the JSON output also?

**Comment by todvora** [comment]
Yes, available in the JSON format too.

**Comment by todvora** [comment]
I'm closing this issue now, but feel free to reopen it or ask again, if you need any more answers.

Best regards,
Tomas
