### ISSUE TITLE
using in nodejs application

### ISSUE THREAD

**Issue by ashishtilara** [variety/variety#125]
how can I use this nodejs application, i have node application that stores any random data objects to mongo. and want to create api endpoint that reads mongo collection and returns all available search keys.

Is it possible with this this library? If so, can I get an example please.

Thank you.

**Comment by todvora** [comment]
Hi @ashishtilara,
The Variety library itself isn't node.js compatible. It is a mongo-shell script, executed from command line in your operating system. Your API endpoint would need to execute a regular binary on your system. That could lead to a serious security threats. 

Having said that, there are several options how to use Variety from a node.js app. You can take our [test helper](https://github.com/variety/variety/blob/6a908273bf216a29eecb588c6cd1f2eedc939421/spec/utils/Tester.js#L44) as an example. It just wraps the command execution and parses JSON output.  Another example could be [variety-cli](https://github.com/variety/variety-cli). It's also a node.js app, built to simplify Variety usage from command line.

If your application already stores data to a MongoDB and has a DB driver installed, maybe it would be better to use this driver to obtain all the keys through it. Either with [MapReduce](https://docs.mongodb.com/manual/core/map-reduce/) or using [Aggregation pipeline](https://docs.mongodb.com/manual/aggregation/). 

Best regards,
Tomas

**Comment by todvora** [comment]
One more thing - you can reference Variety dependency directly from your ```package.json``` as ```variety/variety```. NPM will automatically download the latest version from Github. 

See [package.json](https://github.com/variety/variety-cli/blob/2ad7502a9f53dba31b1b60bc097d051d90d8fc61/package.json#L30) of variety-cli.

**Comment by ashishtilara** [comment]
Thank you @todvora 😄
