### ISSUE TITLE
A bug in <An Easy Example> of README ?

### ISSUE THREAD

**Issue by magicfive** [variety/variety#127]
Hi everyone, 

I am doing some mongodb's schema analysis, and find variety is a cool tool. 

But seems the easy example is wrong ? 

after command 

> mongo test --eval "var collection = 'users'" variety.js"

i got result as : 

    +--------------------------------------------------------------------+
    | key                | types                | occurrences | percents |
    | ------------------ | -------------------- | ----------- | -------- |
    | _id                | ObjectId             |           5 |    100.0 |
    | name               | String               |           5 |    100.0 |
    | bio                | String               |           3 |     60.0 |
    | birthday           | Date                 |           2 |     40.0 |
    | pets               | String (1),Array (1) |           2 |     40.0 |
    | someBinData        | BinData-old          |           1 |     20.0 |
    | someWeirdLegacyKey | String               |           1 |     20.0 |
    +--------------------------------------------------------------------+

As shows above, "pets"'s occurrences should be 2.

**Comment by todvora** [comment]
Hi @magicfive,
Thanks for your report. It's indeed a mistake in the README. It should be 2, as you correctly see in results and as verified in tests ([1](https://github.com/variety/variety/blob/master/spec/BasicAnalysisTest.js#L25), [2](https://github.com/variety/variety/blob/master/spec/assets/ExpectedAscii.js#L10)). Would you like to send a pull request for this issue? 

Best regards,
Tomas

**Comment by magicfive** [comment]
@todvora sure, a moment.

**Comment by todvora** [comment]
Merged, thank you for you contribution!
