### ISSUE TITLE
Reserved keys

### ISSUE THREAD

**Issue by kurteknikk** [variety/variety#130]
Can I use variety.js to easily discover reserverd keys in a mongo colllection ? Or do I have to write custom-code for this ?

The reserved key that i'm specifically interested in is a '.' in a field name eg: ```var rec = {'hello.world':12345}```

**Comment by JamesCropcho** [comment]
Speaking only for myself, I don't understand. It seems you are saying that a `.` in a field name is a reserved key.

Separately, are we generally defining "reserved keys" as keys which are not permitted to be a key by MongoDB for any reason?

**Comment by kurteknikk** [comment]
Maybe "Reserved keys" is not the correct title for this question.

Basically I try to save that document in mongo 3.2 and it fails:

```
rs0:PRIMARY> var x = {'hello.world':123}
rs0:PRIMARY> db.test.insert(x);
2016-10-26T16:47:27.714+0200 E QUERY    [thread1] Error: can't have . in field names [hello.world] :
DBCollection.prototype._validateForStorage@src/mongo/shell/collection.js:248:1
Bulk/this.insert@src/mongo/shell/bulk_api.js:652:17
DBCollection.prototype.insert@src/mongo/shell/collection.js:344:13
@(shell):1:1
```

I never had this issue with mongo 2.4, but with mongo 3.2 i get that error. So it seems to me that a ```.``` is not allowed as part of a field name.

That is what I would like to analyze with variety.js, because I'm porting some data from mongo 2.4 to mongo 3.2 and then those kind of documents will fail.

**Comment by JamesCropcho** [comment]
Hey Kurt,

Good of you to clarify.

I would assume that you can use Variety with MongoDB v2.4, or whichever version accepts your documents, to get a list of all keys, including with nesting, which would be the nontrivial part.

You can then subsequently write a script to go through those keys, locating those which have periods or match whichever other criteria.

Hope this helps. I'll close for now but feel free to re-open for additional advice from me or anyone else.

**Comment by kurteknikk** [comment]
That was my initial instinct too but the problem is that since the key contains a ```.```, there is no way to identify the difference between:
- a ```.``` because of a "key.sub_key" scenario
- a ```.``` because of an invalid key

That's why I've asked this question, to see if there is something in variety that can do this.

P.S I'm already digging in the code to see where is the right place to check invalid keys, maybe I can submit a pull request if the use-case is relevant to this project.

**Comment by TimLudwinski** [comment]
I would just use the mongo 2.6 shell and run `db.upgradeCheckAllDBs()`.

**Comment by kurteknikk** [comment]
That's exactly the right way to do it indeed, thanks @TimLudwinski for your suggestion !
