### ISSUE TITLE
Custom field in table

### ISSUE THREAD

**Issue by jetuuuu** [variety/variety#132]
Hi. How can I change the table? Example:
`
$ mongo test --eval "var collection = 'users'" variety.js
`

| key   | type     |
|-------|----------|
| _id   | ObjectId |
| value | String   |

P.S. Now I made a local patch.

**Comment by todvora** [comment]
Hi @jetuuuu,
Just to be sure - do you want to change the output of Variety? 

The table is, as you already know, hardcoded. There is no configuration regarding the ASCII table itself. But you can write your own plugin for Variety and print anything you want. 

Please check http://plugins.varietyjs.org/details/variety-plugin-csv or http://plugins.varietyjs.org/details/variety-plugin-latex

Would this solve your issue?

Best regards,
Tomas

**Comment by jetuuuu** [comment]
@todvora Yes, I want to change the output of Variety. 
ok… I write plugin for this.

Thank you.

**Comment by todvora** [comment]
Perfect! If you want your plugin to be published at [plugins.varietyjs.org](http://plugins.varietyjs.org/) just add ```variety-plugin``` to keywords in the ```package.json``` and publish your plugin in [NPM registry](https://www.npmjs.com/).

https://github.com/variety/variety-plugins-searcher

Regards,
Tomas
