### ISSUE TITLE
Can I use this in my research

### ISSUE THREAD

**Issue by zainaftab44** [variety/variety#139]
Hi, 
can I use this tool in my research work?

**Comment by todvora** [comment]
Hi @zainaftab44,
Variety is licensed under the [MIT license](https://opensource.org/licenses/MIT), so I see no reason why you couldn't use it in your research.

**Comment by JamesCropcho** [comment]
Hello @zainaftab44 , thanks for asking! Yes, as @todvora writes, we are indeed under MIT. Here's a place to read more about it (https://choosealicense.com/licenses/mit/), but if you're in a hurry, just know that one can use Variety for almost anything.

If you distribute something which has whole or parts of Variety source code inside, as per the MIT license kindly include the license and copyright alongside.

Also importantly, could you kindly let us know if you use Variety for research and what for? I'd love to know.


Good Luck,
James Cropcho

**Comment by JamesCropcho** [comment]
Hey @zainaftab44 , did you end up using Variety? If so, what sort of research? I'd love any links or brief description you might be able to provide us. We would feel additionally vindicated for our efforts!


James
