### ISSUE TITLE
update to not rely on --eval

### ISSUE THREAD

**Issue by landkommunenhippie** [variety/variety#141]
Hi everyone,

the official mongoDB documentation mentions that the eval method is marked as deprecated and will eventually be removed in the future [1]. Are there plans to to deal with this removal already?

[1] https://docs.mongodb.com/manual/reference/method/db.eval/

**Comment by JamesCropcho** [comment]
Tobias ( @landkommunenhippie ), thank you very much for bringing this to our attention.

I have just reached out to a personal contact who is "high up" and relevant to this potential issue.

I will report back what information I may find.

**Comment by landkommunenhippie** [comment]
Hey,
thanks for the quick reply. I am looking forward to the report. :)

Kind regards,
Tobias

**Comment by asya999** [comment]
What’s being deprecated is the server db.eval() function. I don’t see you using that anywhere in the project. 

The mongo shell —eval option doesn’t have anything to do with server-side db.eval() function. 

Asya

**Comment by landkommunenhippie** [comment]
Hi,
as far as I can see they are talking of the db.eval() method in the mongo shell as well as the --eval command.
At least I suggested so. Here is another link to follow: https://jira.mongodb.org/browse/SERVER-17453 
I am sorry if I misunderstood that.

Kind Regards,
Tobias

**Comment by asya999** [comment]
The db.eval() helper in the shell is a wrapper for calling the server $eval command.  That's what's deprecated.   

The only thing I see being used in this project is the --eval command line option to mongo shell, which causes the mongo shell to evaluate the Javascript passed to it.  It does *not* send that code to the server.

https://docs.mongodb.com/manual/reference/program/mongo/index.html#cmdoption-mongo-eval

Asya Kamsky
Lead Product Manager
MongoDB Server

**Comment by landkommunenhippie** [comment]
Hi,

thanks for clarification. Excuse my misunerstanding.
So the ticket can be closed I think.

Kind regards,
Tobias

**Comment by JamesCropcho** [comment]
Aysa ( @asya999 ), it's an honor to have you on the Variety issue tracker! Thank you very much for your prompt and detailed clarification. Also, it's great to hear the good news!
