### ISSUE TITLE
Variety establishes unsecure connections

### ISSUE THREAD

**Issue by hanvinke** [variety/variety#143]
In response to https://answers.launchpad.net/variety/+question/665427:

The problem is severe because it allows MITM-attacks, but can be easily resolved.
First by adding python2-pyopenssl wrapper to the dependencies. (For ARCH users python2-pyopenssl  17.5.0-2)
Next by  opening a terminal and calling 'python2'. Very important detail - since calling 'python' will only bring up version 3, since that is default.
After that follow the rules at https://urllib3.readthedocs.io/en/latest/user-guide.html#ssl :

Certificate verification in Python 2

Older versions of Python 2 are built with an ssl module that lacks SNI support and can lag behind security updates. For these reasons it’s recommended to use pyOpenSSL.

If you install urllib3 with the secure extra, all required packages for certificate verification on Python 2 will be installed:

_pip install urllib3[secure]

If you want to install the packages manually, you will need pyOpenSSL, cryptography, idna, and certifi.

Note

If you are not using macOS or Windows, note that cryptography requires additional system packages to compile. See building cryptography on Linux for the list of packages required.

Once installed, you can tell urllib3 to use pyOpenSSL by using urllib3.contrib.pyopenssl:

>>> import urllib3.contrib.pyopenssl
>>> urllib3.contrib.pyopenssl.inject_into_urllib3()

Finally, you can create a PoolManager that verifies certificates when performing requests:

>>> import certifi
>>> import urllib3
>>> http = urllib3.PoolManager(
...     cert_reqs='CERT_REQUIRED',
...     ca_certs=certifi.where())_

**Comment by todvora** [comment]
Hi @hanvinke,
I think that this is a misunderstanding. This Variety is a "Schema Analyzer for MongoDB". You refer to a [Variety](https://launchpad.net/variety), which "changes the wallpaper on a regular interval using user-specified or automatically downloaded images".

**Comment by hanvinke** [comment]
Yes, I am sorry.

**Comment by todvora** [comment]
No problem :-)
