### ISSUE TITLE
Variety starts up, but everything is unresponsive.

### ISSUE THREAD

**Issue by royketelaar** [variety/variety#144]
Anyone else having this problem or a solution for this? When I boot up I get this registration pop-up, but none of the buttons are responsive. I can move the box and all but the only way to remove it is using xkill command.

![screenshot from 2018-03-30 15-17-27](https://user-images.githubusercontent.com/2485534/38139032-ffccc590-342d-11e8-8775-0a6e9a032e5e.png)

Also the menu options from variety seem to be unresponsive (like when I try to quit or change to the next image)

**Comment by royketelaar** [comment]
Fixed it by purging variety and removing the config files for variety in ./.config/variety

**Comment by todvora** [comment]
Hi @royketelaar,
This is probably a misunderstanding. This repository is about a schema analyzer for MongoDB.

Best regards,
Tomas

**Comment by royketelaar** [comment]
@todvora Oh I see, my bad haha
