### ISSUE TITLE
Can we support JSON in memory or in static file analysis without Mongodb? 

### ISSUE THREAD

**Issue by ivawzh** [variety/variety#147]
Can we support JSON in memory or in static file analysis?

We are not using Mongodb, but we want to analyze some loosely schemaed JSON data. 

Does Variety use Mongo for any particular reasons such as plugins or mongo feature dependency?

**Comment by todvora** [comment]
Hi @ivawzh,
I am afraid Variety can't help you with this. Variety heavily relies on MongoDB as a run environment, data source, uses its built-in functions and pretty much everything is tightly coupled. 

You would have to import your data into a MongoDB instance to analyze them with Variety.

Best regards,
Tomas

**Comment by ivawzh** [comment]
Fair enough. Thanks for the quick response =]
