### ISSUE TITLE
Mongo Java driver - execute variety

### ISSUE THREAD

**Issue by irxn** [variety/variety#149]
I want to know if it is possible to call variety from grails.

I tried:

mongoDB.eval("load(\"/path/to/variety.js\")")
I get this exception:

Caused by: com.mongodb.MongoCommandException: Command failed with error 139: 'ReferenceError: load is not defined :
I want call the method like from command line

mongo datatables --eval \"var collection ='production_BESUCHER'\" /path/to/variety.js
How do I achieve this is grails?

Any ideas?

**Comment by JamesCropcho** [comment]
Does anybody know about using Variety alongside Grails? Alas, I do not know anything about Grails.

**Comment by JamesCropcho** [comment]
Hello all. Well, it sounds like no one knows how to do this. I'm going to close this issue, but anyone, feel free to re-open if you'd like to re-tackle it.
