### ISSUE TITLE
golang execution of variety

### ISSUE THREAD

**Issue by chakrapani123** [variety/variety#150]
hello,

I love this tool and would love to integrate it to for schema analyser for nosql. since its more of a mongo shell execution wondering if there is any alternate way to kick this in golang . i noticed that there is nodejs variety-cli and hoping if there is anything in golang as well
 

thanks much
chakri

**Comment by JamesCropcho** [comment]
Thanks for getting in touch with Variety, Chakri! ( @chakrapani123 )

And thank you very much for the kind words of encouragement to all Variety contributors.

To my knowledge there is no such "binding"/"wrapper" for Variety+Go. (Anyone else know of anything?)

However, Variety is essentially a MongoDB script written in JavaScript. I believe means that it could be executed within any language runtime environment either 1) as a subprocess; or 2) by calling the script via a suitable MongoDB wrapper written for that particular environment, should it exist.

I hope this helps. Let us know if you have follow-up questions, Chakri.


Best,
James
