### ISSUE TITLE
How to use variety with a db with auth?

### ISSUE THREAD

**Issue by YNX940214** [variety/variety#152]
I tried to use variety on a specified database with username and password. I searched and tired a lot of commands but none of them works. May I have an example? Because I think this is a very common situation.

**Comment by todvora** [comment]
Hi,
Could you please try these params (adapted to your actual credentials)?

```
mongo test_db --username="variety_test_user" --password="test" --authenticationDatabase="auth_db" --eval="var collection = 'users';" variety.js
```

**Comment by YNX940214** [comment]
@todvora  Would you please add the "ip:port" part please? That one of the parts bother me.

**Comment by JamesCropcho** [comment]
Thanks for using Variety, YNX.

Hmm…I don't recall: is Variety capable of connecting to a non-`localhost` MongoDB database?

**Comment by YNX940214** [comment]
mongo mongodb://ip:port/db  --username="xx" --password="123" --eval="var collection = 'xxx';" variety.js

**Comment by JamesCropcho** [comment]
Hey YNX, thanks for posting that command.

Did you solve your own issue, i.e. answer your own question?

If so I (or you) will mark this issue as closed.

Happy Friday!

**Comment by YNX940214** [comment]
Yes, solved

**Comment by JamesCropcho** [comment]
Thanks again for asking this and for confirming the working command, @YNX940214.

I opened #270 to track first-class MongoDB URI support in the built-in CLI. I also opened #271 to document the current supported forms: the built-in CLI with `--host` / `--port` / auth flags, plus the direct `mongosh` URI invocation.

Closing this as answered/documented.
