### ISSUE TITLE
Using Variety on MongoDB Atlas databases

### ISSUE THREAD

**Issue by Hellorin** [variety/variety#153]
Hello,

I've been developping a little tool using Variety to explore my database structure. It has been working perfectly on localhost but when I extended the tool to be able to connect to a MongoDB atlas database, I've been having an issue with IP whitelisting.

My command line looks like this:
```
mongo *myClusterMongoDBAtlas* -u *myUsername* -p *myPassword* --quiet --eval "var collection = 'myCollection', outputFormat='json' variety.json"
```

Unfortunately, I have the following error logs:
```
2019-12-14T23:02:30.902+0100 I  NETWORK  [js] Starting new replica set monitor for ***

2019-12-14T23:02:30.902+0100 I  CONNPOOL [ReplicaSetMonitor-TaskExecutor] Connecting to ***

2019-12-14T23:02:30.903+0100 I  CONNPOOL [ReplicaSetMonitor-TaskExecutor] Connecting to ***

2019-12-14T23:02:30.903+0100 I  CONNPOOL [ReplicaSetMonitor-TaskExecutor] Connecting to ***

2019-12-14T23:02:31.136+0100 I  NETWORK  [ReplicaSetMonitor-TaskExecutor] Confirmed replica set for *** is ***

2019-12-14T23:02:31.368+0100 I  NETWORK  [js] Marking host *** as failed :: caused by :: Location40659: can't connect to new replica set master [***], err: AuthenticationFailed: Authentication failed.

*** It looks like this is a MongoDB Atlas cluster. Please ensure that your IP whitelist allows connections from your network.
```

I tried connecting using only the following command line and it works perfectly:
```
mongo *myClusterMongoDBAtlas* -u *myUsername* -p *myPassword*
```
For information, my IP whitelist has been set to 0.0.0.0 (anyone) for all the duration of this test.

Do you have any insights of why when running Variety on my MongoDB atlas cluster, it doesn't work?

Thank you.

David

**Comment by JamesCropcho** [comment]
Hello David,

Thanks for contacting the Variety team.

I'm pretty sure this is the first time we are hearing from a MongoDB Atlas user. Therefore we sadly don't have any comparable past successes/failures of others to reference. However, we will still try and see if we can help.

I myself have not used Atlas.

Does anybody else have any ideas?


―James

**Comment by JamesCropcho** [comment]
Hello again, David. I am sorry that (seemingly) no one knows the answer to your question. I will leave this issue open in the hopes someone will see it and weigh in.

Additionally, if you yourself have acquired any further insight, kindly help all Variety users and share your newfound knowledge by commenting here.


―James

**Comment by billsinc** [comment]
Hello @Hellorin, after installing the `variety-cli` from [https://github.com/variety/variety-cli](https://github.com/variety/variety-cli), I was able to connect using the following syntax:
`variety <database>/<collection> --host <single_hostname>.mongodb.net --port 27017 --tls --authenticationDatabase admin --authenticationMechanism SCRAM-SHA-1 --username <username> --password <password>`

**Comment by JamesCropcho** [comment]
Bill, on behalf of all Variety users thank you very much for answering David's question (and all who come along after him).

David, let us know how it goes!


―James

**Comment by Hellorin** [comment]
Thank you for your answer @billsinc . The problem was actually related to the URL provided by MongoDB Atlas. I was trying to use it as is but I needed to use one of the 3 nodes' url instead.

Thank you for your help.
