### ISSUE TITLE
Should we distribute Variety via NPM? Others?

### ISSUE THREAD

**Issue by JamesCropcho** [variety/variety#55]
Hey,

Do you all think we should have an NPM package for Variety, also distributing in this way?

Or perhaps, just to throw it out there, via another package manager?

-James

**Comment by todvora** [comment]
Hi all,
I recently experimented with the NPM platform and created package called [variety-cli](https://www.npmjs.com/package/variety-cli). It's basically a wrapper around Variety itself. The main benefits are:

- simple installation for NPM users (only usual ```npm install variety-cli -g``` needed).
- Automatic download of the latest Variety.js library from the Variety github repository.
- Cleaner command line syntax (```variety webapp/users``` for analysing collection *users* in database *webapp*, npm adds automatically variety to bin path). 

I hope it could lower the barrier for any new users. The don't need to download Variety manually, switching command line paths, providing all the ```--eval``` syntax. 

What do you think? Is it the way to go? Do you find it useful? Is it actually ok to use the Variety name in the package name? Would it be interesting to later incorporate [the repository](https://github.com/todvora/variety-cli) into Variety organisation on Github?

Thanks,
Tomas

**Comment by imoapps** [comment]
way to go, i do think this is a brilliant idea , it would be great if there was similar implementation for some python packages

**Comment by JamesCropcho** [comment]
Quite awesome, Tomáš. I always appreciate your initiative.

I'm very down to integrate this into the Variety organization (and yes, of course it's fine to use the name Variety in the name variety-cli).

**Comment by todvora** [comment]
OK, after several iterations the code seems to work, it is tested and little bit documented. Please feel free to comment it or request any modifications. I'll do my best :-)

**Comment by JamesCropcho** [comment]
Thanks, Tomáš. This is a step in the right direction.  —J
