### ISSUE TITLE
Where is the log file?

### ISSUE THREAD

**Issue by alexbfree** [variety/variety#74]
Hi, your instructions say that you should tail the log file to see percentage complete if it is taking a long time. I don't see any log files appearing in the variety.js folder... Where is the log file in question and what is its filename?

**Comment by todvora** [comment]
Hi Alex,
Variety itself does not produce any log files. The mentioned log is MongoDB process log. The location depends on your configuration of mongod process. Please see http://docs.mongodb.org/manual/reference/configuration-options/ for more details. 

Best regards,
Tomas
