### ISSUE TITLE
Program should output the name of collection

### ISSUE THREAD

**Issue by Acetolyne** [variety/variety#77]
When printing the output nowhere in the ouput does it show which collection the data is for. When you print the collections you then have to rely on the filename to tell you which collection you are looking at. It would be benificial to add the name of the collection into the output of the program for easier documentation.

**Comment by JamesCropcho** [comment]
I agree that this would be a helpful addition. Thanks for thinking of it, Jon. Let's see if can get your pull merged into `master`, now.

-James
