### ISSUE TITLE
Feedback requested: collection as array feature implemented

### ISSUE THREAD

**Issue by Acetolyne** [variety/variety#80]
Guys I love this project alot and have been working hard to give some contributions in my latest push to my repo I have added the ability to specify an array for the collection name. It still works with the single string as well. I have made a couple fixes to ensure that json formatting still works, I may make some minor output formatting changes but it seems to work great. Please test and let me know what you think the syntax is now 
mongo test --eval "var collection = 'users'" variety.js        For a single collection
mongo test --eval "var collection = ['users', 'articles', 'collection3']" variety.js      For an array 

In the next day or two I should also have a working copy that will do all collections in the database I was thinking of using "var mode = recursive"  Please test and give feedback then I will do a pull request if the feature is liked. Thanks have a wonderful day!!

**Comment by JamesCropcho** [comment]
Wow, thank you for your kind words, Jon! Let us know what we can do to support your endeavors with Variety.

Since you've done all you'd mentioned here already on pull request https://github.com/variety/variety/pull/81, unless you thin otherwise I'll close this and move the conversation there. -J
