### ISSUE TITLE
eval is deprecated since MongoDB version 3.0

### ISSUE THREAD

**Issue by bitboxx** [variety/variety#85]
eval() is being deprecated. Is there any other way to run Variety that is future proof?

Mentioned on the official reference manual:
(http://docs.mongodb.org/manual/reference/method/db.eval/)

The [reasoning](https://jira.mongodb.org/browse/SERVER-17453) behind the deprecation.

**Comment by todvora** [comment]
Hi @bitboxx,
Thank you for the information. Variety itself does not execute any server side JavaScript. The ```eval``` is used only to provide some params to the mongo shell => client side. So I think we are OK in this case. Am I right?

Thank you,
Tomas

**Comment by bitboxx** [comment]
I see and good to know. Thank you Tomas for the explanation.

**Comment by JamesCropcho** [comment]
Smart message, @bitboxx. Thanks for helping keep us aware!

Yes, this is important enough that I double-checked. It (at least) looks like the shell argument is not deprecated: http://docs.mongodb.org/manual/reference/program/mongo/


James
