### ISSUE TITLE
Support of MongoDB 3.0

### ISSUE THREAD

**Issue by todvora** [variety/variety#87]
It seems that Variety itself works without any problems on MongoDB version 3.0. But the tests requiring authorization and creating users are failing. They use [db.addUser](http://docs.mongodb.org/v2.6/reference/method/db.addUser/). This method is deprecated since 2.6 and replaced by [db.createUser](http://docs.mongodb.org/manual/reference/method/db.createUser/). The ```addUser``` method works on both 2.4 and 2.6, does not exist anymore in 3.0. 

To keep our tests compatible with 2.4 (Travis-CI), 2.6 and 3.0, we have to adapt the test behavior to actual version of the db on runtime.

**Comment by JamesCropcho** [comment]
Good sleuthing and future-proofing, Tomáš.

So maybe the Travis-CI suite should run once on 2.x and once on 3.x. Would that make sense?

Or maybe we should only support 3.0 moving forward and have a 2.x branch? That might be better, now that I think about it, but curious about your thoughts. Let me know.

**Comment by todvora** [comment]
In the Travis-CI is not possible to test two different versions of MongoDB together. But I really like the idea of more different branches for different versions. Maybe we could really create branch for the old 2.4 version. Then it could be possible to handle 2.6-3.0 in current master branch. I'll try it and share the results.

**Comment by JamesCropcho** [comment]
Sure—I'm down for the branching strategy you suggest. It seems best to handle as many previous versions as possible on the `master`/3.0/latest branch.

Sharing the results? Yes, please do!
