### ISSUE TITLE
Plugin infrastructure

### ISSUE THREAD

**Issue by todvora** [variety/variety#92]
Hi all,
Recently we received a PR for the latex support. Requests like this requires lots of coding from the author, long discussions under the PR, dealing with test suite of Variety and is complicated on all sides. Maybe we should come up with some form of a plugins infrastructure, that would allow contributors extending Variety functionality without modifying the main library itself. 

I have tried to integrate a plugins functionality and it could be done with only minor changes of Variety. You can see the first implementation [here](https://github.com/todvora/variety/tree/plugin-infrastructure). 

I also created one [sample plugin](https://github.com/todvora/variety-plugin-csv), that outputs results in the CSV format and has configurable delimiter. In the same way could be implemented also [the latex output](https://github.com/todvora/variety-plugin-latex).

Plugins can be attached simply by adding a parameter like this:
```
mongo test --eval "var collection = 'users'; var plugins='/path/to/plugin/index.js';" variety.js
```
More details can be found in the sample plugin readme. The dynamic loading of plugins is based on the ```load``` function provided by the Mongo shell.  

The sample plugin is compatible with the [NPM](https://www.npmjs.com/) specification, but does not depend on node/npm anyhow. It allows easier testing and providing metadata in a standard format. Around this format can be later build a variety-plugin directory (for example like [gitbook plugins](http://plugins.gitbook.com/)).

The main Variety library is still standalone, no dependencies or additional requirements. Without the plugin param behaves exactly the same way as before. 

What do you think? Does it make sense? 

Thanks,
Tomas

**Comment by joggino** [comment]
I'm in favour, it makes the process a lot simpler to use and people can add what they need without bloating the initial library for everyone.

**Comment by JamesCropcho** [comment]
I think that sounds like a brilliant idea, Tomáš. And I do like that it is NPM-compatible and also(!) not requiring any additional runtime dependencies.

Yes, in theory we could "dog food" the plugin functionality, meaning we would take all but the core functionality out of Variety core and into plugins, themselves. But that's based on everyone time availability and is certainly not a dependency, just a thought.

I'm amenable to moving forward on this.


James

**Comment by todvora** [comment]
Hi all,
just up-to-date info:

On the page [variety.herokuapp.com](https://variety.herokuapp.com/) runs a minimalistic plugins registry. All the data are taken online from the npm registry database. To add your own plugin, just publish it on npm with keyword ```variety-plugin```. The page is powered by [this simple express server](https://github.com/todvora/variety-plugins-registry) and uses [variety-plugins-searcher](https://github.com/todvora/variety-plugins-searcher).

I also published two demo/test plugins - [csv](https://www.npmjs.com/package/variety-plugin-csv) and [latex](https://www.npmjs.com/package/variety-plugin-latex). 

@joggino - please feel free to fork, change or adapt the latex plugin. It's based on your idea and it would be cool, if you wanted to continue on it or publish your own version.

The Variety [adaptation](https://github.com/todvora/variety/tree/plugin-infrastructure) PR will follow soon. 

If someone would like to hack on the [registry]((https://github.com/todvora/variety-plugins-registry) ) and wanted to build some nice site around it, I would be really glad. All pull requests are welcome.

Thanks,
Tomas

**Comment by JamesCropcho** [comment]
Hey Tomáš, this is great! And cool that the listing autopopulates from NPM.

Variety is starting to feel like a very robust ecosystem with big efforts from you, sir.

**Comment by todvora** [comment]
Directory update - added some basic design, output of plugin readme, download and npm links, tags...

**→[variety.herokuapp.com](https://variety.herokuapp.com/)**
