### ISSUE TITLE
RangeError

### ISSUE THREAD

**Issue by kimquy06** [variety/variety#93]
Hi there,

I tried variety.js with my mongodb which has about 1.7M items and met this error: RangeError: Maximum call stack size exceeded at variety.js:284
failed to load: variety.js

Regards, 
Quy

**Comment by todvora** [comment]
Hi Quy,
Thank you very much for your bug report. I was able to find the source of this error and fix it. It should be OK in [the latest release](https://github.com/variety/variety/tree/daf0061ee1a8184d8cf0caf2c13efb3e6c52d740). 

Please let me know, if you hit other issues. 

Best regards,
Tomas

**Comment by JamesCropcho** [comment]
Thanks for finding the bug, Quy. It hopefully now works for you, and you have already made larger numbers work for all Variety users :)

Let us know if you face further problems with this issue.

James
