### ISSUE TITLE
Using feh is uncommented

### ISSUE THREAD

**Issue by erikdubois** [variety/variety#97]
Hi,

can you uncomment the "feh" lines in the two scripts to set and get the wallpaper.
The lines work on I3 archlinux and i3 linux mint 17.1 cinnamon.

 Feh
 sed "s/\ /\n/g" ~/.fehbg | grep \'

Feh - commented, as it may cause problems with Nautilus, (see bug https://bugs.launchpad.net/variety/+bug/1047083)
 feh --bg-scale "$WP" 2> /dev/null

**Comment by todvora** [comment]
Hi @erikdubois, 
This github repository is for Variety - MongoDB schema analyzer. If you want to report bug or solution for [Variety - wallpaper changer](http://peterlevi.com/variety/), you should probably report it on [launchpad](https://launchpad.net/variety).

Best regards,
Tomas

**Comment by erikdubois** [comment]
wow ok ?!

**Comment by todvora** [comment]
Hi @erikdubois,
May I close this issue? Is there anything I can help with? 

Also - thank you for your message anyway. It let me realize, that there is another Variety project :-) 

Have a nice day,
Tomas
