### ISSUE TITLE
Unclear README.md section "See Progress When Analysis Takes a Long Time"

### ISSUE THREAD

**Issue by amannm** [variety/variety#99]
The directions here are not clear. I can't figure out what "tailing the log" means in the context of MongoDB. Is this a MongoDB operation or an OS operation? Which log am I supposed to be tailing?

And then you say MongoDB provides this for me. That sounds really great... but then I can't find any information about where it is provided.

**Comment by JamesCropcho** [comment]
Hey Variety-core, let's keep our answer on this thread and out of the README unless we see others asking the same.

Amann, `tail` is a *nix commandline tool which you may use to view realtime output of a log, .e.g. a MongoDB log. You can read more here: https://en.wikipedia.org/wiki/Tail_(Unix), and many other places on the web, no doubt.

**Comment by todvora** [comment]
Hi all,
another already closed log / tail question is https://github.com/variety/variety/issues/74.

@amannm: you can read more about log location and configuration in the MongoDB documentation: http://docs.mongodb.org/manual/reference/configuration-options/

Best regards,
Tomas
